import Head from "next/head";
import Homepage from "./Homepage";

export default function Home() {
  return (
    <>
      <Head>
        <title>OTO ILAN</title>
        <meta name="description" content="Generated by yigitozdamar" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Homepage />
      </main>
    </>
  );
}
